### ISSUE TITLE
disconnessione dopo pochi secondi

### ISSUE THREAD

**Issue by acuplush** [bigmoby/hassio-repository-addon#4]
ciao, sto provando il tuo addon ma si disconnette dopo pochi secondi e non capisco il motivo.
ho creato un nuovo tunnel nel fritzbox e inserito i dati nel tuo addon sull'istanza HA della seconda casa ma non funziona.
cè qualche accorgimento che mi sfugge?
grazie

![wireguardclient](https://github.com/user-attachments/assets/35929be2-b859-4169-af8a-529d70b36683)

**Comment by bigmoby** [comment]
Hi @acuplush, 
Please, for future cases, write in English and use the add-on repository at https://github.com/bigmoby/addon-wireguard-client.
From what I see in your log, you've misconfigured the add-on due to this limitation described in the README: https://github.com/bigmoby/addon-wireguard-client?tab=readme-ov-file#known-issues
